title: "Hadar's Homepage"
logo: '/me.jpg'
description: "Welcome to my page"
theme: jekyll-theme-minimal
permalink: pretty
show_downloads: true

plugins:
  - jekyll-remote-theme

# Link the custom CSS file
include:
  - assets/css/style.css


