
title: "Hadar's homepage"
description: "Talk data to me"
cover_image: '/Computer_science.jpg'

plugins:
  - jekyll-remote-theme

remote_theme: vszhub/not-pure-poole

include:
  - README.md  # If you want to make sure README.md is processed
