
title: "Hadar's homepage"
logo : '/me.jpg'
description: "Welcome to my page"
cover_image: '/Computer_science.jpg'
theme: jekyll-theme-Minimal
permalink: pretty

plugins:
  - jekyll-remote-theme








