title: "Hadar's Homepage"
description: "Welcome to my page"
theme: jekyll-theme-minimal
permalink: pretty
show_downloads: true

# Add plugins if necessary
plugins:
  - jekyll-remote-theme

# Add a custom CSS file to include Google Fonts
remote_theme: pages-themes/minimal@v0.2.0
include:
  - assets/css/style.css





