theme: jekyll-theme-slate
title: Hadar's homepage
description: Hellow everyone, welcome to my page!


I am an MSc student at the Weizmann Institute of Science. My goal is to become a skilled bioinformatician!

My research focuses on the vaginal microbiome and its correlation with age, BMI, menopause status, and nutrition.
