title: "Hadar Klimovski"
description: "Welcome to my personal space!"
theme: jekyll-theme-modernist
permalink: pretty
show_downloads: false
title_align: center

# Customize colors (only works if you create a CSS file)
custom_css: "style.css"
